select * from WASADMIN.CUSTOMER

select * from WASADMIN.UBTB_CUSTOMERCONTACT

select * from WASADMIN.ADDRESS

select * from WASADMIN.ADDRESSLINKS

select * from WASADMIN.UBTB_CUSTOMERCONNECTIONDETAILS

select * from WASADMIN.CUSTOMERDOCDTL

select * from WASADMIN.PERSONDETAILS

select * from WASADMIN.UBTB_PERSONEDUCATIONDETAILS

select * from WASADMIN.ORGDETAILS

select * from WASADMIN.UBVW_CUST_EMPLOYMENTDTL

select * from WASADMIN.UBTB_CUSTEXTERNALAPPREF

select * from WASADMIN.PERSONPORTFOLIO

select * from WASADMIN.UBTB_GENBUSINESSIDDTL

select * from WASADMIN.USERDETAIL