--select * from acct
--select * from acdw



select FXDH.CCY AS CCY, sum(FXDH.CCYAMT) AS AMT from FXDH
JOIN PBAD on FXDH.CUST= PBAD.ACCNO
WHERE PBAD.CUSTOMER='000036' AND FXDH.BR='99'
group by FXDH.ccy

union 

select DLDT.CCY AS CCY, sum(DLDT.CCYAMT) AS AMT from DLDT
JOIN PBAD on DLDT.CNO= PBAD.ACCNO
WHERE PBAD.CUSTOMER='000036' AND DLDT.BR ='99'
group by ccy

UNION

select ACCT.CCY AS CCY, sum(ACDW.CCYAMT) AS AMT from ACCT
JOIN PBAD on ACCT.CNO= PBAD.ACCNO
JOIN ACDW ON ACCT.ACCOUNTNO = ACDW.ACCOUNTNO 
WHERE PBAD.CUSTOMER='000036' AND ACDW.BR = '99'
group by ccy

union

select SPSH.CCY AS CCY, sum(SPSH.FACEAMT) AS AMT from SPSH
JOIN PBAD on SPSH.CNO= PBAD.ACCNO
JOIN SECM ON SPSH.SECID=SECM.SECID
WHERE PBAD.CUSTOMER='000036' AND SECM.PRODUCT='SECUR' AND SECM.PRODTYPE='FI' AND SPSH.BR ='99' 
group by SPSH.CCY

Union

select SPSH.CCY AS CCY, sum(SPSH.FACEAMT) AS AMT from SPSH
JOIN PBAD on SPSH.CNO= PBAD.ACCNO
JOIN SECM ON SPSH.SECID=SECM.SECID
WHERE PBAD.CUSTOMER='000036' AND SECM.PRODUCT='SECUR' AND SECM.PRODTYPE='EQ' AND SPSH.BR ='99' 
group by SPSH.CCY

UNION

select SLDH.CCY AS CCY, sum(COMPROCAMT) AS AMT from SLDH
JOIN PBAD on SLDH.CNO= PBAD.ACCNO
WHERE PBAD.CUSTOMER='000036' AND SLDH.BR ='99'
group by ccy

UNION

select RPDT.CCY AS CCY, sum(RPDT.FACEAMT) AS AMT from RPDT
JOIN PBAD on RPDT.CNO= PBAD.ACCNO
WHERE PBAD.CUSTOMER='000036' AND RPDT.BR ='99'
group by ccy

UNION

select SWDT.NOTCCY AS CCY, sum(SWDT.NOTCCYAMT) AS AMT from SWDH
JOIN PBAD on SWDH.CNO= PBAD.ACCNO
JOIN SWDT ON SWDH.DEALNO = SWDT.DEALNO
WHERE PBAD.CUSTOMER='000036' AND SWDH.BR ='99'
group by SWDT.NOTCCY

UNION

select FFDH.CUSTFEECCY AS CCY, sum(FFDH.CCYAMT) AS AMT from FFDH
JOIN PBAD on FFDH.CNO= PBAD.ACCNO
WHERE PBAD.CUSTOMER='000036' AND FFDH.BR ='99'
group by FFDH.CUSTFEECCY