select * from CBS.CBVW_GENERICCODE
where CBDESCRIPTION like 'EX TRATE%'

select * from CBS.CBVW_GENERICCODE
where 1=1
--CBCODETYPE=
AND CBSUBCODETYPE='001'

select * from CBS.CBVW_GENERICCODE
Where CBCODETYPE='2009'
order by CBDESCRIPTION

select * from CBS.CBVW_GENERICCODE
Where CBCODETYPE='-1'
and CBSUBCODETYPE in ('2007','2008','2009','2010','2011','2012')
order by CBDESCRIPTION

select * from CBS.CBTB_CODE
where CBCODEBK='1062'

select * from CBS.CBTB_CODE
where CBPARENTID=4339