select 
A.CUSTOMERCODE asCIFKey,
GetDate() AS ExtractDate,
'D' AS RecordID,
'JM' AS LocalCountryCode,
A.BRANCHSORTCODE AS TransitNo, 
dbo.svfGetCodeInformation(-1,A.CUSTOMERTYPE) as CustomerType,
B.SURNAME AS Lastname,
NULL AS SecondLastName,
B.FORENAME AS FirstMiddleName,
B.UBNAMEATBIRTH AS Alias,
A.UBCREATEDTTM AS CustomerSince,
dbo.svfGetCodeInformation('017',B.SEX) AS Sex,
dbo.svfGetCodeInformation('002',B.TITLE) AS CustomerTitle,
dbo.svfGetCodeInformation('023',A.PREFERREDLANGUAGE) AS CustomerLanguage,
B.DATEOFBIRTH AS BirthDate,
A.TAXNUMBER AS TaxID,
D.ADDRESSLINE1 AS AddressLineOne,
D.ADDRESSLINE2 AS AddressLineTwo,
D.ADDRESSLINE5 AS City,
D.ADDRESSLINE6 AS Province,
D.ADDRESSLINE7 AS CountryOfAddress,
B.UBCITIZENSHIP AS CountryOfCitizenship,
B.COUNTRYOFDOMICILE AS CountryOfDomicile,
NULL AS ClientTypeDesc,
NULL AS OccupationCode,
dbo.svfGetCodeInformation('1073',E.UBPOSITION) AS OccupationDesc,
F.UBCUSTCONNECTIONNAME AS Employer,
NULL AS WorkPhone,
(SELECT UBCONTACTMEDIUMDETAILS FROM MSDEV.WASADMIN.UBTB_CUSTOMERCONTACT
WHERE UBCUSTOMERCODE=A.CUSTOMERCODE AND UBCONTACTMEDIUMTYPE='001') AS HomePhone,
(SELECT UBCONTACTMEDIUMDETAILS FROM MSDEV.WASADMIN.UBTB_CUSTOMERCONTACT
WHERE UBCUSTOMERCODE=A.CUSTOMERCODE AND UBCONTACTMEDIUMTYPE='004') AS Email,
NULL AS NameOfSpouse,
NULL AS SpousalTaxID,
G.ORGNAME AS NameLineOne,
NULL AS NameLineTwo,
NULL AS SICCOde,
B.UBCOUNTRYOFBIRTH AS CountryOfBirth,
B.UBPLACEOFBIRTH AS CityOfBirth,
B.FATHERNAME AS FatherName,
B.UBMOTHERMAIDENNAME AS MotherName,
NULL AS ChildName1,
NULL AS ChildName2,
H.UBDOCUNIQUEREF AS TradingName,
G.ESTABLISHEDDATE AS DateOfBusinessEstablished,
H.UBTRADINGREGNUM AS RegistrationNo,
H.UBPLACEISSUEREG AS LocationOfRegisterdOffice,
I.SCDESCRIPTIONBUSINESS AS BusinessTypeDesc,
NULL AS BusinessNature,
dbo.svfGetCodeInformation('1086',G.UBISSUBSIDIARYORPARENT) AS BusinessStructure,
NULL AS KeyContactPerson,
(SELECT UBCONTACTMEDIUMDETAILS FROM MSDEV.WASADMIN.UBTB_CUSTOMERCONTACT
WHERE UBCUSTOMERCODE=A.CUSTOMERCODE AND UBCONTACTMEDIUMTYPE='001' AND UBISPREFERREDCONTACT='Y') AS KeyContactPersonPhone,
NULL AS PrincipleOwner,
dbo.svfGetSignings(A.CUSTOMERCODE) AS SignatureAuthroity,
G.NOOFEMPLOYEES AS NoOfFullTime,
NULL AS NoOfPartTime,
dbo.svfGetCodeInformation('1089',G.UBPRIMARYBUSINESSACTIVITY) AS AnnualSalesExpectedSource,
G.ANNUALTURNOVER AS AnnualSalesExpectedAmount,
NULL AS SupplierOne,
NULL AS SupplierTwo,
NULL AS AptUnitFloor
from  MSDEV.WASADMIN.CUSTOMER A
LEFT JOIN MSDEV.WASADMIN.PERSONDETAILS B ON A.CUSTOMERCODE=B.CUSTOMERCODE
LEFT JOIN MSDEV.WASADMIN.CUSTOMERDOCDTL C ON C.CUSTOMERCODE=A.CUSTOMERCODE AND C.DOCTYPE='021'
LEFT JOIN MSDEV.WASADMIN.ADDRESS D On D.DOCID = C.DOCID 
LEFT JOIN MSDEV.WASADMIN.UBTB_CUSTEMPLOYMENTDETAILS E ON E.CUSTOMERCODE=A.CUSTOMERCODE
LEFT JOIN MSDEV.WASADMIN.UBTB_CUSTOMERCONNECTIONDETAILS F ON F.UBCUSTCONNECTIONIDPK = E.UBCUSTCONNECTIONID
LEFT JOIN MSDEV.WASADMIN.ORGDETAILS G On A.CUSTOMERCODE=G.CUSTOMERCODE
LEFT JOIN MSDEV.WASADMIN.CUSTOMERDOCDTL H ON H.CUSTOMERCODE=A.CUSTOMERCODE AND H.DOCTYPE='Legal'
LEFT JOIN MSDEV.SCOTIA.SCOTIA_CORPORATEINFO I ON I.SCCUSTNO=A.CUSTOMERCODE
where A.CUSTOMERCODE = '000133'